// Single source of truth for technology logos, vendored under public/logos/.
// SVG where the vendor publishes one; raster only where no clean SVG exists.
export const logos = {
    Bash: '/logos/bash.svg',
    C: '/logos/c.svg',
    Rust: '/logos/rust.svg',
    Java: '/logos/java.svg',
    TypeScript: '/logos/typescript.svg',
    PostgreSQL: '/logos/postgresql.svg',
    SQLite: '/logos/sqlite.svg',
    Redis: '/logos/redis.svg',
    RabbitMQ: '/logos/rabbitmq.svg',
    Bun: '/logos/bun.svg',
    Drizzle: '/logos/drizzle.png',
    React: '/logos/react.svg',
    Svelte: '/logos/svelte.svg',
    Astro: '/logos/astro.svg',
    Tailwind: '/logos/tailwind.svg',
    Tauri: '/logos/tauri.svg',
    Kubernetes: '/logos/kubernetes.svg',
    AWS: '/logos/aws.svg',
    GCP: '/logos/gcp.svg',
    OVH: '/logos/ovh.svg',
    Cloudflare: '/logos/cloudflare.svg',
    Terraform: '/logos/terraform.svg',
    Terragrunt: '/logos/terragrunt.png',
    ArgoCD: '/logos/argocd.svg',
    GitHub: '/logos/github.svg',
    GitLab: '/logos/gitlab.svg',
    Keycloak: '/logos/keycloak.svg',
    Vault: '/logos/vault.svg',
    NeuVector: '/logos/neuvector.jpg',
    CNPG: '/logos/cnpg.svg',
    Prometheus: '/logos/prometheus.svg',
    Grafana: '/logos/grafana.svg',
    ExternalDNS: '/logos/external-dns.png',
    ExternalSecrets: '/logos/external-secrets.svg',
    Docker: '/logos/docker.svg',
    Traefik: '/logos/traefik.svg',
    MySQL: '/logos/mysql.svg',
    SpringBoot: '/logos/spring.svg',
    NestJS: '/logos/nestjs.svg',
    LinkedIn: '/logos/linkedin.svg',
} as const;

export type LogoKey = keyof typeof logos;
