backend:
  name: github
  repo: antonin-suzor/antonin-suzor-com
  branch: dev
  base_url: https://sveltia-cms-auth.antonin-a7d.workers.dev/
  commit_messages:
    create: "[CMS] Create {{collection}} {{slug}}"
    update: "[CMS] Update {{collection}} {{slug}}"
    delete: "[CMS] Delete {{collection}} {{slug}}"
    uploadMedia: "[CMS] Upload {{path}}"
    deleteMedia: "[CMS] Delete {{path}}"
    openAuthoring: "[CMS] {{message}}"

media_folder: static/blogmedia
public_folder: /blogmedia
display_url: https://antonin-suzor.com/
locale: en

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: posts
    identifier_field: title
    label: Posts
    label_singular: Post
    description: Blog posts for antonin-suzor.com
    folder: src/lib/blog
    create: true
    hide: false
    extension: md
    format: yaml-frontmatter
    frontmatter_delimiter: "---"
    slug: "{{slug}}"
    fields:
      - name: title
        label: Title
        widget: string
        required: true
      - name: description
        label: Description
        widget: string
        required: true
      - name: thumbnail
        label: Thumbnail
        widget: image
        required: false
      - name: thumbnail_alt
        label: Thumbnail Alt Text
        widget: string
        required: false
      - name: created_at
        label: Creation date
        widget: datetime
        required: true
        type: date
        picker_utc: false
        default: '{{now}}'
      - name: updated_at
        label: Last edit date
        widget: datetime
        required: false
        type: datetime-local
        picker_utc: false
      - name: body
        label: Body
        widget: markdown
        required: true
